"""Command registry and command ID definitions."""

from enum import IntEnum
from typing import Dict
from .base import CommandSpec
from ..protocol.constants import (
    CMD_VOLTAGE_REQUEST,
    CMD_CURRENT_STATUS_REQUEST,
    CMD_CAPACITY_STATUS_REQUEST,
    CMD_SERIAL_NUMBER_REQUEST,
    CMD_ALLOW_DISCHARGE,
    CMD_DISALLOW_DISCHARGE,
    CMD_ALLOW_CHARGE,
    CMD_DISALLOW_CHARGE,
)


class CommandId(IntEnum):
    """BMS command identifiers (Command Low bytes)."""
    VOLTAGE_REQUEST = CMD_VOLTAGE_REQUEST
    CURRENT_STATUS_REQUEST = CMD_CURRENT_STATUS_REQUEST
    CAPACITY_STATUS_REQUEST = CMD_CAPACITY_STATUS_REQUEST
    SERIAL_NUMBER_REQUEST = CMD_SERIAL_NUMBER_REQUEST
    ALLOW_DISCHARGE = CMD_ALLOW_DISCHARGE
    DISALLOW_DISCHARGE = CMD_DISALLOW_DISCHARGE
    ALLOW_CHARGE = CMD_ALLOW_CHARGE
    DISALLOW_CHARGE = CMD_DISALLOW_CHARGE


COMMANDS: Dict[CommandId, CommandSpec] = {}