"""Protocol constants for Orion 1000 BMS communication."""

START: int = 0xEA
END: int = 0xF5
PRODUCT_ID_DEFAULT: int = 0xD1
COMMAND_HIGH: int = 0xFF

# Command codes (Command Low bytes)
CMD_VOLTAGE_REQUEST: int = 0x02
CMD_CURRENT_STATUS_REQUEST: int = 0x03
CMD_CAPACITY_STATUS_REQUEST: int = 0x04
CMD_SERIAL_NUMBER_REQUEST: int = 0x11
CMD_ALLOW_DISCHARGE: int = 0x19
CMD_DISALLOW_DISCHARGE: int = 0x1A
CMD_ALLOW_CHARGE: int = 0x1B
CMD_DISALLOW_CHARGE: int = 0x1C